module.exports = function () {
return {
products: [
{ id: 1, name: "Happy Shirt", category: "Shirts",
description: "A shirt for a happy occasion", price: 50 },
{ id: 2, name: "Edgy Shirt", category: "Shirts",
description: "Fashionable shirt", price: 50 },
{ id: 3, name: "Tank Top", category: "Shirts",
description: "For work and working out", price: 40 },
{ id: 4, name: "Sweater", category: "Shirts",
description: "Great for those cold nights at home",
price: 55.99 },
{ id: 5, name: "Turtleneck", category: "Shirts",
description: "Edgy yet proper", price: 62 },
{ id: 6, name: "Jean Shirt", category: "Shirts",
description: "For an old school style", price: 72.99 },
{ id: 7, name: "Dress Shirt", category: "Shirts",
description: "Great for work", price: 35 },
{ id: 8, name: "Jeans", category: "Pants",
description: "Casual style", price: 60 },
{ id: 9, name: "Slacks", category: "Pants",
description: "Comfy and stlish", price: 72 },
{ id: 10, name: "Dress Pants", category: "Pants",
description: "When you need to give a good impression", price: 69.99 },
{ id: 11, name: "Ripped Jeans", category: "Pants",
description: "Goes great with the edgy shirt", price: 65 },
{ id: 12, name: "Pantaloons", category: "Pants",
description: "16th Century style brought back", price: 20 },
{ id: 13, name: "Baseball Cap", category: "Hats",
description: "You can customize with your favorite team", price: 15 },
{ id: 14, name: "Cowboy Hat", category: "Hats",
description: "A head turner indeed", price: 20 },
{ id: 15, name: "Ten Gallon Hat", category: "Hats",
description: "Standard texas style", price: 40 },
{ id: 16, name: "Black Belt", category: "Belts",
description: "Sometimes you just need a belt", price: 10 },
{ id: 17, name: "Brown Belt", category: "Belts",
description: "Better when you have brown shoes", price: 5 },
{ id: 18, name: "Full Suit", category: "Outfits",
description: "Something to impress those at work", price: 150 },
{ id: 19, name: "Pajamas", category: "Outfits",
description: "For when you're ready to sleep", price: 120 },
{ id: 20, name: "Cowboy Costume", category: "Outfits",
description: "Great for the upcoming halloween season", price: 175 }
],
orders: []
}
}